### PR TITLE
Update ngx  project package

### PR DESCRIPTION
**Pull request by BernieJ**
update ngx  project package

### CODE REVIEW

**Comment by BernieJ** [comment]
Upgrade npm package also please :)

**Comment by cwilsn** [comment]
Thanks for this.  We are actually using it with no issues with angular 16.  Can you update the PR so the range of valid versions is from 14 and includes 16?

**Comment by cwilsn** [comment]
Sorry, that's not what I had in mind-- I just meant to allow 14-17 in the peer dependencies.  How about revert that last change so your PR is what it was originally?  I'll do some testing after that's merge to allow more versions.

Thanks for the help!

**Comment by BernieJ** [comment]
Sorry only got to this now and for misunderstanding. I can make a change to only 14-17 in the peer dependencies.

I remembered now I was thinking of updating only the peer dependencies but I thought it would be contridictory if peer dependecies are set to 14- 17 but the actual package dependencies are set to only 15 and wasn't sure how npm, yarn would give someone installing the dependencies warnings that the package version is incorrect

**Comment by cwilsn** [comment]
Yeah, if you want to make the peer dependencies 14-17 that would be perfect.  The dependencies being set to a specific version is fine, that just means that's the version of packages the library is currently being developed against.  The peer dependencies are the versions the package should work correctly against.

Thanks for the help!

**Pull request merged**
